name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.2'  # Gunakan Flutter yang mendukung Dart 3.7.2

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test
